### PR TITLE
TRANSPORT now tries harder to send you to a different starting location.

### PR DESCRIPTION
**Pull request by luciensadi**

### CODE REVIEW

**Comment by EmpireMUD** [comment]
I want to suggest a better way than 50 tries. Either roll a random index from 0 to N-2 and add 1 if >= the index of your current location; OR iterate over start location and if each entry is a valid target, roll a random number to determine whether to switch to it as the target.

**Comment by EmpireMUD** [comment]
Hilarious edge case: the map generator only places 1 Tower of Souls. What happens here in that case?

**Comment by luciensadi** [comment]
I actually tried it with 1 Tower, which is how my map generated. It just leaves you in the same place with no lag.

Random index once sounds like it would work, but has the edge case of 1 tower (random index between 0 and -1 will fail). Iterating 0->N would give an increasingly smaller chance of transporting to the later towers, and would fail with the 1 tower edge case.

If you want, I can re-implement it with the random index algorithm that includes a fix for the edge case, but the code as it stands doesn't have a performance hit and seems to function correctly.

**Comment by EmpireMUD** [comment]
Actually if you keep rolling progressively smaller chances like !number(0, num_found_so_far) you get the same chance each time. Some other parts of the code use this method but I’m not near my computer to find an example

**Comment by luciensadi** [comment]
Changed logic. It rolls once, and if it matches the current index then increments by one; if this overflows the array then it goes back to index 0. Also renamed a variable for clarity.

**Comment by EmpireMUD** [comment]
This looks good to me

**Pull request merged**
